name: RTUBloodEffect
version: '${version}'
main: com.github.ipecter.rtu.bloodeffect.RTUBloodEffect
api-version: 1.13
softdepend: [ PlaceholderAPI, ProtocolLib ]
authors: [ IPECTER (이팩터), Mkkas3145 (Original) ]
description: RTU PLUGINS - Blooding on the Hit Area
website: https://github.com/IPECTER/RTUBloodEffect
commands:
  rtube:
    usage: /rtube reload
    description: /rtube reload
permissions:
  rtube.reload:
    description: Plugin reload
    default: op
  rtube.use:
    description: Blood Effect Using
    default: true
  rtube.toggle:
    description: Blood Effect Toggle
    default: true
  rtube.toggle.other:
    description: Other Player Blood Effect Toggle
    default: op
libraries:
  - net.kyori:adventure-platform-bukkit:4.3.0
  - net.kyori:adventure-text-minimessage:4.13.0